### ISSUE TITLE
location attachment document

### ISSUE THREAD

**Issue by timoweiss** [locator-kn/cor#10]
What are the requirements?
- loading paged attachments by location id
- comments, likes?

**Comment by sigoetti** [comment]
define: what is an attachement? .doc, .exe, ,.csv, .pdf? or also movies and sound?

**Comment by timoweiss** [comment]
video/audio/images - you cant handle pdfs or something like that in the app?! ;)

**Comment by michaelknoch** [comment]
images/videos/audio are impressions, no discussions. So we wont need comments.

GET location/{locationId}/impressions

```
[{
    user: 23123213123,
    date: "isostring",
    type: "audio",
    content: "pathtoaudio.mp3"
}, ...]
```

```
{
    ...
    type: "image"
    content: "pathtoimg.jpg"
}
```

```
{
    ...
    type: "video"
    content: "pathtovideo.mp4"
}
```

Discuss:
- file format
- size
- camera only, or support filepicker?
- pagination

**Comment by timoweiss** [comment]
- `camera only, or support filepicker`:
  - backend doesn't care ;)
- `images/videos/audio are impressions, no discussions.`
  - so there are nowhere comments/likes/orsomething because we dont have "discussions" in the app? :D

I would rename the `content` to `path` (and then `"path": "/picture/{id}/name.ext"`) because it's a bit more "RESTy".

**Comment by SteffenGorenflo** [comment]
An Impression object looks like this: 

``` js
{
  user_id: "userId",
  location_id: "locationId",
  data: "pathToTheFile", // or text if the impression is text (see below)
  type: "typeOfTheImpression" // e.g. audio,
  file_id: "fileId"
}
```

So the routes for getting each type of impression looks now like this

``` js
GET /locations/impression/audio/{fileId}/{name}.{ext} Get audio
GET /locations/impression/image/{fileId}/{name}.{ext} Get Image
GET /locations/impression/video/{fileId}/{name}.{ext} Get video
```

(There is no extra route for getting the impression "Text". Its already in the Impression Object of the location)
