### ISSUE TITLE
Find location by title

### ISSUE THREAD

**Issue by sigoetti** [locator-kn/cor#13]
it should be possible to search a location by it's title. (not case sensitive)

**Comment by timoweiss** [comment]
related: #14

**Comment by sigoetti** [comment]
done. commit 5592a2736712f83d88f2d3b30888e9ac3180ccd5
and 00f862b0089e919d1a39e9b86505974d8316dac3 in ms-location.

please test.

**Comment by sigoetti** [comment]
todo: add google search to find title

**Comment by timoweiss** [comment]
The implemented route works, but I think we need to extend the functionality. 
I gonna create a new issue with a more precise description with what is needed.
