### ISSUE TITLE
route conflicts (location by name)

### ISSUE THREAD

**Issue by timoweiss** [locator-kn/cor#14]
there are currently two definitions for the path `/locations/{locationId}` which results in a conflict:
`Error: New route /locations/{locationId} conflicts with existing /locations/{locationId}`

https://github.com/locator-kn/cor/blob/master/lib/location.js#L7-L19 points to `handler.getLocationById` (which seems to be correct)

https://github.com/locator-kn/cor/blob/master/lib/location.js#L106-L118 points to `handler.getLocationByName`

**Comment by timoweiss** [comment]
@sigoetti any news on that issue?

**Comment by sigoetti** [comment]
working on it..

**Comment by sigoetti** [comment]
done. commit 5592a2736712f83d88f2d3b30888e9ac3180ccd5
and 00f862b0089e919d1a39e9b86505974d8316dac3 in ms-location.

please test!

**Comment by SteffenGorenflo** [comment]
no longer a route conflict --> fixed
