### ISSUE TITLE
Location API wishes

### ISSUE THREAD

**Issue by sigoetti** [locator-kn/cor#2]
expected data from frontend:
-title of location (required)
-coordinates long/lat (required)
-description
-categories (to be discussed...)

{
"title": "Meinesuperlocation",
"coord":{"long": "8.75","lat":"47.12"},
 "description": "i love this place, but only with 140 characters description",
"category": {"cat1":"category1","cat2":"category2", "cat3":"category2"}
}

**Comment by timoweiss** [comment]
all possible properties should be available after creation (eg. property `favorites` with value `0`). 

edit: I think the `favorites` should be an array with userids.

**Comment by sigoetti** [comment]
also to add according to the design:
-viewed
-liked
-listed in trip (???)

**Comment by timoweiss** [comment]
liked -> favorites
I think we won't add a "viewed" count for the first version. 
When a location is in a journey, the location doesn't know. Theres only a reference in the journey document.
