### ISSUE TITLE
get locations by user (userId)

### ISSUE THREAD

**Issue by markusheilig** [locator-kn/cor#29]
frontend-teams need a route to get all locations created by a given user (userId).

**Comment by timoweiss** [comment]
@markusheilig how fast do you need it? @sigoetti how fast can you do it?

**Comment by sigoetti** [comment]
just fixed the error in createNewLocation but need to add the user id. but i can start to work on it right now.

**Comment by timoweiss** [comment]
alright: I would name the route `/locations/users/{userId}`

**Comment by sigoetti** [comment]
please test! (not yet perfect)
Commit 6313c19 in cor and 850dcac in ms-location

**Comment by timoweiss** [comment]
Looks like you forgot to pass the param `userId` to the service here:
https://github.com/locator-kn/cor/blob/master/handler/locationHandler.js#L101-L103

you need to read the userId from the route params:
`request.basicSenecaPattern.userId = request.params.userId;`

**Comment by timoweiss** [comment]
ah sry, my bad. not to the basicSenecaPattern.
the issue is that you used request.query. but it is request.params :)

**Comment by timoweiss** [comment]
and the property for the user id is named `user_id` instead of `userId`:
https://github.com/locator-kn/ms-location/blob/master/lib/database.js#L41

**Comment by timoweiss** [comment]
but with this changes, everthing looks good to me :) maybe you could add some semicolons and spaces here and there :)

**Comment by markusheilig** [comment]
thanks @sigoetti for the fast implementation. 
unfortunately, a GET request on https://locator-app.com/api/v2/locations/users/{someValidUserId}
returns the following error object:  {"statusCode":404,"error":"Not Found"}

could you also deploy this route on swagger? this makes it so much easier to test :-)

**Comment by timoweiss** [comment]
@markusheilig if its not on swagger, its not deployed ;) I deployed it right now.
