### ISSUE TITLE
POST /locations/new should be POST /locations

### ISSUE THREAD

**Issue by timoweiss** [locator-kn/cor#30]
according to REST, the route to create a new location should be only `/locations`

**Comment by sigoetti** [comment]
changed back to /locations. getting "util is not defined" back from ms-location. i'm working on that....

**Comment by timoweiss** [comment]
@sigoetti if you need any help, push your changes to a separate branch and let me help you :)

**Comment by sigoetti** [comment]
thanks, i found the mistake. i forgot to add the utils. pushing...
