### ISSUE TITLE
/locations/search?term=searchterm&lat=47&long=9

### ISSUE THREAD

**Issue by timoweiss** [locator-kn/cor#41]
Response should contain locations from database and results from google

**TODO:**
- searchterm: encoding? base64?
- discuss whether lat/long is required or optional
  - maybe use location of IP if nothing supplied
- can we use this route for map search and location-create?
- response schema? esp. google results

@locator-kn/backend @locator-kn/frontend please collaborate!

**Comment by timoweiss** [comment]
https://developers.google.com/places/web-service/search

**Comment by timoweiss** [comment]
```
{
  "locator": [{}, {}, {}, {}, {}],
  "google": [{}, {}, {}]
}
```

**Comment by sigoetti** [comment]
from google maps api (above):

> radius — Defines the distance (in meters) within which to bias place results. The maximum allowed radius is 50 000 meters. Results inside of this region will be ranked higher than results outside of the search circle; however, prominent results from outside of the search radius may be included

searching for locations around a specified lat/long this leads to 20 results every time no matter how large the radius is. 
- i suggest to have a radius of 100m and to take the first five results from google to present the user.

**Comment by sigoetti** [comment]
- so far, i need a set of coordinates for the actual implementation for the google search.
- as there's both a title search for "searchByName" and title recommendation at creating a location, we can use the same route.  
- google doesn't use "title" for the title of the location but "name". there's some remodeling of the json data needed.

**Comment by timoweiss** [comment]
Can you provide a sample response from google that we can discuss what we need?

**Comment by markusheilig** [comment]
will the google response objects have the same data structure as the locator-location results?
this would simplify object handling a lot for both frontend-teams!

of course, the differentiation between google-locations and locator-locations is still needed in the final result-object (e.g. the way @timoweiss suggested [here](https://github.com/locator-kn/cor/issues/41#issuecomment-175775377)).

**Comment by sigoetti** [comment]
this is a sample for one location google gives back:

``` json
{
  "formatted_address": "Spanierstraße 5, 78467 Konstanz, Deutschland",
  "geometry": {
    "location": {
      "lat": 47.6687714,
      "lng": 9.1763339
    }
  },
  "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/cafe-71.png",
  "id": "8b021c19f376f3a0ccb342e03e05cbccec843710",
  "name": "Rheinterrasse Konstanz | Restaurant Café Bar",
  "photos": [
    {
      "height": 612,
      "html_attributions": [
        "<a href=\"https://maps.google.com/maps/contrib/110856542118596310009/photos\">Jan Meier-Henkel</a>"
      ],
      "photo_reference": "CmRdAAAAz4HtYaoBYF93e6R-r6Msej9-4vuaSHryLCfTEIiQ0g9vjccXCNHrlSZA2j5qpbr9yqOIKVD4cNCcMd0jlu9aNTJemgAKmj1Ul6BjstQ9DDtwhBaz3B80EDikICJb0mFGEhCn-j0_xwxgkZT-ZlRAUPTUGhQrWIkmnsw-UtYhW_v-cTxCvvaBZg",
      "width": 816
    }
  ],
  "place_id": "ChIJQxPQGwL3mkcRSyRXGQ3eH2Q",
  "rating": 4,
  "reference": "CoQBgAAAAGNgeADIQZIL7alznd_a3l_X5dZMUOWYsRqw51rp5SZNF8Wa9KPKcmFLq6OHrjswuvQinE51B_Yd_D4OXSpzbZyA5MjouQvGSfRmaXI_eOt4_l5IRXIL4X6M3BBL8cATJm7oJXQS8Zlj5TYrYQJ8d52HR_E5QiXUhpzbhFlE4dwkEhDdWrKHsm-SwpOsq2hrpEZeGhQpQpWN3PI1mJiQ_puaSHCkwyKI0A",
  "types": [
    "cafe",
    "bar",
    "restaurant",
    "food",
    "store",
    "point_of_interest",
    "establishment"
  ]
}
```

there is some parsing into locator's standards needed. there will be five json objects in an array as suggested above. 
as we need the same route for location-search and location-create why don't we let the frontend ask two requests instead of merging the results in the backend? this would us give more flexibility when and what to show the user.

**Comment by timoweiss** [comment]
Screenshot from the design:
![screen shot 2016-01-29 at 8 37 25 nachm](https://cloud.githubusercontent.com/assets/5221667/12686080/2874ff24-c6c8-11e5-81c5-ebe91fac9d4c.png)
~80% of the shown data is obviously not available

**Comment by timoweiss** [comment]
``` json
{
    "_id": "8b021c19f376f3a0ccb342e03e05cbccec843710",
    "title": "Rheinterrasse Konstanz | Restaurant Café Bar",
    "geotag": {
        "type": "Point",
        "coordinates": [
          9.1763339,
          47.6687714
        ]
      }
}
```

TODO: extend, feel free

**Comment by sigoetti** [comment]
to do: deliver google results only, if they are really close by. (google delivers results from new york if it finds nothing)

also apply changes for #62
