### ISSUE TITLE
route for update the own password

### ISSUE THREAD

**Issue by timoweiss** [locator-kn/cor#56]

**Comment by sigoetti** [comment]
- user needs to be logged in to change the password. 
- does it need additional confirmation by email? 
- is old password needed to change the password?

**Comment by timoweiss** [comment]
I would say:
- yes
- no
- yes

:smiley: 
What do you think?

**Comment by sigoetti** [comment]
we can leave out the email and just give the user feedback within the app.

@locator-kn/frontend please don't forget to let the users enter the new password twice to check for typos
