### ISSUE TITLE
location image upload

### ISSUE THREAD

**Issue by timoweiss** [locator-kn/cor#6]
with creation of different image resolutions.
discuss:
- scaffolding location document
- creating/writing _ids immediately to the host doc (location)
- running this service in a own process

@SteffenGorenflo @sigoetti

**Comment by sigoetti** [comment]
- for the different image resolutions we could use something like this: https://github.com/EyalAr/lwip
- there will be a lot of independent image uploads therefore it should have it's own handler. 
- separating image and location data upload when opening a new location. -> 2 POSTs

**Comment by SteffenGorenflo** [comment]
already done in https://github.com/locator-kn/cor/issues/20 --> close
