### ISSUE TITLE
/location/search without search String

### ISSUE THREAD

**Issue by Niwonneb** [locator-kn/cor#62]
A route is needed to search for nearby Locations without a search String for the "Bist du vielleicht hier?" screen.
Also make the search better.

**Comment by Niwonneb** [comment]
Or even better make the search String optional

**Comment by Niwonneb** [comment]
Please make it not produce an error
(Bad Request
\"&#x7d;&#x3f;long\" is not allowed)

**Comment by sigoetti** [comment]
route is getting completely refractored at the moment. 
for testing use postman, swagger has it's problems with the optional query. 
query like this locations/search?long=9.169753789901733&lat=47.66868204997508
