### ISSUE TITLE
GET /locations/search/{locationName?} fuzzy search

### ISSUE THREAD

**Issue by sigoetti** [locator-kn/cor#65]
mongodb currently only finds exact matches. find a way to do a fuzzy search.

test this: https://docs.mongodb.org/manual/reference/operator/query/text/#op._S_text

google finds these other ideas:
- http://blog.mongodb.org/post/95839709598/how-to-perform-fuzzy-matching-with-mongo-connector
- http://ilearnasigoalong.blogspot.ch/2013/10/efficient-techniques-for-fuzzy-and.html

**Comment by markusheilig** [comment]
what about something similar to SQL's 'LIKE' query?
is this a possible solution? -> http://stackoverflow.com/questions/3305561/how-do-i-query-mongodb-with-like

**Comment by sigoetti** [comment]
thanks for the hint. is built in since #66
